In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/jobs.csv")

In [ ]:
df.shape

(85470, 11)

In [ ]:
df.info

<bound method DataFrame.info of                        job_title              job_type  \
0        trưởng phòng kinh doanh  nhân viên chính thức
1      nhân viên qc ngành cơ khí  nhân viên chính thức
2          trưởng phòng đấu thầu  nhân viên chính thức
3          home textile designer  nhân viên chính thức
4           nhân viên kinh doanh  nhân viên chính thức
...                          ...                   ...
85465         bảo trì trang trại  nhân viên chính thức
85466       nhân viên kinh doanh  nhân viên chính thức
85467               bim modeller  nhân viên chính thức
85468         nhân viên gia công  nhân viên chính thức
85469           business analyst  nhân viên chính thức

               position_level         city     experience  \
0      trưởng nhóm , giám sát  hồ chí minh  lên đến 1 năm
1                   nhân viên  hồ chí minh     trên 1 năm
2      trưởng nhóm , giám sát  hồ chí minh      5 - 7 năm
3                   nhân viên     hưng yên     5 - 15 năm
4                   nhân viên  hồ chí minh     trên 1 năm
...                       ...          ...            ...
85465               nhân viên    toàn quốc  không yêu cầu
85466               nhân viên  hồ chí minh     trên 1 năm
85467               nhân viên  hồ chí minh     trên 2 năm
85468               nhân viên  hồ chí minh      1 - 2 năm
85469               nhân viên       hà nội      2 - 3 năm

                                                  skills  \
0                                                    NaN
1      production planning staff, chuyên viên iso, th...
2      trưởng phòng xây dựng, trưởng phòng đấu thầu, ...
3                                                    NaN
4                                                    NaN
...                                                  ...
85465                                                NaN
85466                                                NaN
85467                                                NaN
85468                                                NaN
85469          sales analyst, analysts, business analyst

                                              job_fields             salary  \
0         kinh doanh, bán hàng, nội ngoại thất, xây dựng  15 tr - 50 tr vnd
1      vận hành sản xuất, sản xuất, qc), quản lý chất...   8 tr - 11 tr vnd
2      điện, xây dựng, điện tử, điện lạnh, dầu khí, đ...  20 tr - 30 tr vnd
3      dệt may, nghệ thuật, da giày, thiết kế, mỹ thu...    800 - 1,500 usd
4           tư vấn, bán sỉ, bán lẻ, kinh doanh, bán hàng  10 tr - 50 tr vnd
...                                                  ...                ...
85465                                                NaN  10 tr - 15 tr vnd
85466                                                NaN   8 tr - 10 tr vnd
85467                                                NaN  15 tr - 25 tr vnd
85468                                                NaN    8 tr - 9 tr vnd
85469                                                NaN  lên đến 25 tr vnd

       salary_min  salary_max unit
0            15.0        50.0  vnd
1             8.0        11.0  vnd
2            20.0        30.0  vnd
3            20.0        37.5  usd
4            10.0        50.0  vnd
...           ...         ...  ...
85465        10.0        15.0  vnd
85466         8.0        10.0  vnd
85467        15.0        25.0  vnd
85468         8.0         9.0  vnd
85469         0.0        25.0  vnd

[85470 rows x 11 columns]>

In [ ]:
df.head()

,job_title,job_type,position_level,city,experience,skills,job_fields,salary,salary_min,salary_max,unit
0,trưởng phòng kinh doanh,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,lên đến 1 năm,NaN,"kinh doanh, bán hàng, nội ngoại thất, xây dựng",15 tr - 50 tr vnd,15.0,50.0,vnd
1,nhân viên qc ngành cơ khí,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,"production planning staff, chuyên viên iso, th...","vận hành sản xuất, sản xuất, qc), quản lý chất...",8 tr - 11 tr vnd,8.0,11.0,vnd
2,trưởng phòng đấu thầu,nhân viên chính thức,"trưởng nhóm , giám sát",hồ chí minh,5 - 7 năm,"trưởng phòng xây dựng, trưởng phòng đấu thầu, ...","điện, xây dựng, điện tử, điện lạnh, dầu khí, đ...",20 tr - 30 tr vnd,20.0,30.0,vnd
3,home textile designer,nhân viên chính thức,nhân viên,hưng yên,5 - 15 năm,NaN,"dệt may, nghệ thuật, da giày, thiết kế, mỹ thu...","800 - 1,500 usd",20.0,37.5,usd
4,nhân viên kinh doanh,nhân viên chính thức,nhân viên,hồ chí minh,trên 1 năm,NaN,"tư vấn, bán sỉ, bán lẻ, kinh doanh, bán hàng",10 tr - 50 tr vnd,10.0,50.0,vnd

In [ ]:
df.isnull().sum()

job_title             7
job_type              0
position_level        0
city                 32
experience            0
skills            11294
job_fields         7625
salary                0
salary_min            0
salary_max            0
unit                  0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(40531)

Dataset gồm 85.470 tin tuyển dụng.

Có 11 thuộc tính.

Các cột skills và job_fields có nhiều giá trị thiếu.

Cần tiến hành làm sạch dữ liệu.