In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving jobs.csv to jobs.csv

In [ ]:
df = pd.read_csv("jobs.csv")

In [ ]:
df.isnull().sum()

job_title             7
job_type              0
position_level        0
city                 32
experience            0
skills            11294
job_fields         7625
salary                0
salary_min            0
salary_max            0
unit                  0
dtype: int64

In [ ]:
#Xử lý missing

df["skills"] = df["skills"].fillna("Unknown")

df["job_fields"] = df["job_fields"].fillna("Unknown")

df["city"] = df["city"].fillna("Unknown")

In [ ]:
#Xoá trùng

df = df.drop_duplicates()

In [ ]:
#Chuẩn hoá text

df["job_title"] = df["job_title"].str.strip()

df["city"] = df["city"].str.strip()

In [ ]:
#Kiểm tra salary

df[["salary_min","salary_max"]].describe()

         salary_min    salary_max
count  44939.000000  44939.000000
mean      12.445354     19.364688
std       15.045288     16.435982
min        0.000000      0.000000
25%        8.000000     12.000000
50%       10.000000     15.000000
75%       15.000000     22.000000
max      900.000000    700.000000

In [ ]:
#Tạo lương trung bình

df["avg_salary"] = (
    df["salary_min"] +
    df["salary_max"]
)/2

In [ ]:
#Lọc IT Jobs

it_keywords = [
    "developer",
    "software",
    "engineer",
    "backend",
    "frontend",
    "fullstack",
    "data",
    "ai",
    "devops",
    "it"
]

In [ ]:
pattern = "|".join(it_keywords)

df_it = df[
    df["job_title"]
    .str.lower()
    .str.contains(pattern, na=False)
]

In [ ]:
#Lưu dữ liệu sạch

df_it.to_csv(
    "clean_it_jobs.csv",
    index=False
)